Rename pig jar from loadfunc to storage to reflect it supports both reading and writing. Patch by Jeremy Hanna, reviewed by brandonwilliams for CASSANDRA-2303
git-svn-id: https://svn.apache.org/repos/asf/cassandra/branches/cassandra-0.7@1080090 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/contrib/pig/bin/pig_cassandra b/contrib/pig/bin/pig_cassandra
--- a/contrib/pig/bin/pig_cassandra
+++ b/contrib/pig/bin/pig_cassandra
@@ -24,13 +24,13 @@ for jar in $cassandra_home/lib/*.jar $cassandra_home/build/lib/jars/*.jar; do
     CLASSPATH=$CLASSPATH:$jar
 done
 
-# cassandra_loadfunc jar.
-LOADFUNC_JAR=`ls -1 $cwd/../build/*.jar`
-if [ ! -e $LOADFUNC_JAR ]; then
-    echo "Unable to locate cassandra_loadfunc jar: please run ant." >&2
+# cassandra_storage jar.
+STORAGE_JAR=`ls -1 $cwd/../build/*.jar`
+if [ ! -e $STORAGE_JAR ]; then
+    echo "Unable to locate cassandra_storage jar: please run ant." >&2
     exit 1
 fi
-CLASSPATH=$CLASSPATH:$LOADFUNC_JAR
+CLASSPATH=$CLASSPATH:$STORAGE_JAR
 
 if [ "x$PIG_HOME" = "x" ]; then
     echo "PIG_HOME not set: requires Pig >= 0.7.0" >&2
