use conf/cassandra-env.sh in place of defaults
Patch by eevans; reviewed by Brandon Williams for CASSANDRA-1407

git-svn-id: https://svn.apache.org/repos/asf/cassandra/trunk@986940 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/debian/init b/debian/init
--- a/debian/init
+++ b/debian/init
@@ -18,18 +18,24 @@ PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 CONFDIR=/etc/cassandra
 JSVC=/usr/bin/jsvc
-JVM_MAX_MEM="1G"
-JVM_START_MEM="128M"
-JMX_PORT="8080"
 
 # The first existing directory is used for JAVA_HOME if needed.
 JVM_SEARCH_DIRS="/usr/lib/jvm/java-6-openjdk /usr/lib/jvm/java-6-sun"
 
 [ -e /usr/share/cassandra/apache-cassandra.jar ] || exit 0
 [ -e /etc/cassandra/cassandra.yaml ] || exit 0
+[ -e /etc/cassandra/cassandra-env.sh ] || exit 0
+
+# Read Cassandra environment file.
+. /etc/cassandra/cassandra-env.sh
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+if [ -z "$JVM_OPTS" ]; then
+    echo "Initialization failed; \$JVM_OPTS not set!" >&2
+    exit 3
+fi
 
 # If JAVA_HOME has not been set, try to determine it.
 if [ -z "$JAVA_HOME" ]; then
@@ -111,13 +117,8 @@ do_start()
         -errfile "&1" \
         -outfile /var/log/$NAME/output.log \
         -cp `classpath` \
-        -Xmx$JVM_MAX_MEM \
-        -Xms$JVM_START_MEM \
         -Dlog4j.configuration=log4j-server.properties \
-        -Dcom.sun.management.jmxremote.port=$JMX_PORT \
-        -Dcom.sun.management.jmxremote.ssl=false \
-        -Dcom.sun.management.jmxremote.authenticate=false \
-        $JVM_EXTRA_OPTS \
+        $JVM_OPTS \
         org.apache.cassandra.thrift.CassandraDaemon
 
     if ! is_running; then return 2; fi
