Revert "allow running stress from build classes" and "Add stress tool to binaries"
This reverts commits cb7a931ffcda61392d59c995c6733c20e47c98f0 and 9b746daf7f2d0725b6ebe678dfbedb303b71bf57.

diff --git a/tools/stress/bin/stressd b/tools/stress/bin/stressd
--- a/tools/stress/bin/stressd
+++ b/tools/stress/bin/stressd
@@ -19,19 +19,22 @@
 DESC="Stress Test Daemon"
 
 if [ "x$CLASSPATH" = "x" ]; then
-    
-    # execute from the build dir.
-    if [ -d `dirname $0`/../../build/classes ]; then
-        for directory in `dirname $0`/../../build/classes/*; do
-            CLASSPATH=$CLASSPATH:$directory
-        done
-    else
-        if [ -f `dirname $0`/../lib/stress.jar ]; then
-            CLASSPATH=`dirname $0`/../lib/stress.jar
-        fi
+    # Cassandra class files.
+    if [ ! -d `dirname $0`/../../../build/classes/main ]; then
+        echo "Unable to locate cassandra class files" >&2
+        exit 1
     fi
 
-    for jar in `dirname $0`/../../lib/*.jar; do
+    # Stress class files.
+    if [ ! -d `dirname $0`/../build/classes ]; then
+        echo "Unable to locate stress class files" >&2
+        exit 1
+    fi
+
+    CLASSPATH=`dirname $0`/../../../build/classes/main
+    CLASSPATH=$CLASSPATH:`dirname $0`/../../../build/classes/thrift
+    CLASSPATH=$CLASSPATH:`dirname $0`/../build/classes
+    for jar in `dirname $0`/../../../lib/*.jar; do
         CLASSPATH=$CLASSPATH:$jar
     done
 fi
